name: "CD: codedoc"
on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
    branches:
      - main

env:
  PROJECT_PATH: "./lib"
jobs:
  publish:
    name: "Publish to npm"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
      actions: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Install dependencies"
        shell: bash
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          npm install
      - name: "Build"
        shell: bash
        working-directory: ${{ env.PROJECT_PATH }}
        run: npm run build
      - name: "Publish"
        shell: bash
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
