name: "CI Checks"
on:
  workflow_dispatch:
  push:
jobs:
  check:
    name: "Build Verification and Unit Tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
